name: Lithology Brewing
favicon: null
layout_spectrum: 0.76874
typography_spectrum: 0.34057
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: Lithology Brewing
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#fb4700'
    - '#101531'
    - '#777a8e'
    - '#b7b9c4'
  brandStrength: 0.6875
  lightness: 0.6875
  saturation: 0.9375
  rhythmicContrast: 0
purpose: []
